datasources:
  adb:
    url: jdbc:oracle:thin:@adbsidecar_high?TNS_ADMIN=/path/to/wallet
    username: ADMIN
    password: changeme
  oracle:
    url: jdbc:oracle:thin:@//localhost:1521/FREEPDB1
    username: SYSTEM
    password: changeme
  postgres:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: changeme
spring:
  data:
    mongodb:
      uri: mongodb://admin:changeme@localhost:27017/admin
